spring.application.name=ledger


#application.security.jwt.secret-key=dGVzdHRlc3R0ZXN0dGVzdHRlc3R0ZXN0dGVzdHRlc3R0ZXN0dGVzdA==
#application.security.jwt.expiration=86400000
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/payment_ledger
#spring.datasource.username=postgres
#spring.datasource.password=...
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true