package com.payment.ledger.util;

import com.payment.ledger.entity.User;
import com.payment.ledger.entity.Wallet;
import com.payment.ledger.enums.AccountStatus;
import com.payment.ledger.enums.Role;
import com.payment.ledger.enums.WalletStatus;
import com.payment.ledger.repository.UserRepository;
import com.payment.ledger.repository.WalletRepository;
import com.payment.ledger.service.JwtService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import com.payment.ledger.repository.NotificationRepository;
import com.payment.ledger.repository.LedgerEntryRepository;

import java.io.File;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.util.Properties;

@SpringBootTest
public class DatabaseSeeder {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private WalletRepository walletRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JwtService jwtService;

    @Autowired
    private NotificationRepository notificationRepository;

    @Autowired
    private LedgerEntryRepository ledgerEntryRepository;

    private void cleanUpUser(String email) {
        userRepository.findByEmail(email).ifPresent(u -> {
            // Delete notifications first
            notificationRepository.deleteAll(notificationRepository.findByUserOrderByCreatedAtDesc(u));
            
            // Delete wallet and its ledger entries
            walletRepository.findByUser(u).ifPresent(w -> {
                ledgerEntryRepository.deleteAll(ledgerEntryRepository.findByWalletIdOrderByCreatedAtDesc(w.getId()));
                walletRepository.delete(w);
                walletRepository.flush();
            });
            
            // Delete the user
            userRepository.delete(u);
            userRepository.flush();
        });
    }

    @Test
    public void seedDatabaseForJMeter() throws Exception {
        System.out.println("SEEDING DATABASE FOR JMETER LOAD TEST...");

        // Clean up existing sender and receiver users
        cleanUpUser("sender@jmeter.com");
        cleanUpUser("receiver@jmeter.com");

        // Create sender user
        User sender = new User();
        sender.setUsername("sender_jmeter");
        sender.setEmail("sender@jmeter.com");
        sender.setPasswordHash(passwordEncoder.encode("12345678"));
        sender.setRole(Role.USER);
        sender.setEnabled(true);
        sender.setAccountStatus(AccountStatus.ACTIVE);
        userRepository.save(sender);
        sender.setEnabled(true);
        sender.setAccountStatus(AccountStatus.ACTIVE);
        userRepository.saveAndFlush(sender);

        Wallet senderWallet = new Wallet();
        senderWallet.setUser(sender);
        senderWallet.setBalance(new BigDecimal("1000.0000"));
        senderWallet.setCurrency("INR");
        senderWallet.setStatus(WalletStatus.ACTIVE);
        walletRepository.save(senderWallet);

        // Create receiver user
        User receiver = new User();
        receiver.setUsername("receiver_jmeter");
        receiver.setEmail("receiver@jmeter.com");
        receiver.setPasswordHash(passwordEncoder.encode("12345678"));
        receiver.setRole(Role.USER);
        receiver.setEnabled(true);
        receiver.setAccountStatus(AccountStatus.ACTIVE);
        userRepository.save(receiver);
        receiver.setEnabled(true);
        receiver.setAccountStatus(AccountStatus.ACTIVE);
        userRepository.saveAndFlush(receiver);

        Wallet receiverWallet = new Wallet();
        receiverWallet.setUser(receiver);
        receiverWallet.setBalance(BigDecimal.ZERO);
        receiverWallet.setCurrency("INR");
        receiverWallet.setStatus(WalletStatus.ACTIVE);
        walletRepository.save(receiverWallet);


        // Generate JWT token for sender
        String token = jwtService.generateToken(sender);

        // Write properties to file
        Properties props = new Properties();
        props.setProperty("jwt.token", token);
        props.setProperty("receiver.wallet.id", receiverWallet.getId().toString());
        props.setProperty("api.url", "http://localhost:8080");
        props.setProperty("api.host", "localhost");
        props.setProperty("api.port", "8080");

        File jmeterDir = new File("jmeter");
        if (!jmeterDir.exists()) {
            jmeterDir.mkdirs();
        }

        File propertiesFile = new File(jmeterDir, "config.properties");
        try (FileOutputStream out = new FileOutputStream(propertiesFile)) {
            props.store(out, "JMeter load test configurations generated by DatabaseSeeder");
        }

        System.out.println("SEEDING COMPLETED SUCCESSFULLY.");
        System.out.println("JWT Token: " + token);
        System.out.println("Receiver Wallet ID: " + receiverWallet.getId());
        System.out.println("Properties written to: " + propertiesFile.getAbsolutePath());
    }
}
